In [48]:
using LinearAlgebra
using Plots
using Ripserer
using Distances
using Plots
using DataFrames, CSV
using DelimitedFiles
using AbstractAlgebra
using MultivariateStats #for pca
using IterativeSolvers
using NearestNeighbors
include("mv_function_bens_alg.jl")


mv (generic function with 1 method)

In [49]:
#Globals
K = 10 # in KNN
#OG_K = 10
ITER = 30    # iterations of algorithm
KKK = 2
break_count = KKK #iterations before breakingxs
min_loss = 1000
min_loss_2 = 1000
input_file ="./cool_big_data.csv"
output_file ="./point_color"

a_ = []
b_ = []
c_ = []
d_ = []
e_ = []
f_ = []

loss_ = []
loss_2 = []


Any[]

In [50]:
# Loss function 0.5 instead of pi

function loss_1(points, coord_ab, coord_cd, coord_ef)
    a_cd = mod(coord_cd[points[1]],1.0)
    b_cd = mod(coord_cd[points[2]],1.0)

    c_ab = mod(coord_ab[points[3]],1.0)
    d_ab = mod(coord_ab[points[4]],1.0)

    e_ab = mod(coord_ab[points[5]],1.0)
    f_ab = mod(coord_ab[points[6]],1.0)

    e_cd = mod(coord_cd[points[5]],1.0)
    f_cd = mod(coord_cd[points[6]],1.0)

    a_ef = mod(coord_ef[points[1]],1.0)
    b_ef = mod(coord_ef[points[2]],1.0)
    c_ef = mod(coord_ef[points[3]],1.0)
    d_ef = mod(coord_ef[points[4]],1.0)

    # ab_coords
    loss =(0.5 - mod(c_ab-d_ab, 1.0))^2 + (0.5 - mod(e_ab-f_ab,1.0))^2
    #loss += abs(0.25 - mod(c_ab - e_ab, 1.0))+ abs(0.25 - mod(e_ab - d_ab, 1.0)) + abs(0.25 - mod(d_ab - f_ab,1.0)) + + abs(0.25 - mod(f_ab - c_ab, 1.0))
    #cd_coords
    loss += (0.5 - mod(a_cd-b_cd, 1.0))^2 + (0.5 - mod(e_cd-f_cd,1.0))^2
    #loss += abs(0.25 - mod(a_cd - e_cd, 1.0)) + abs(0.25 - mod(e_cd - b_cd, 1.0)) + abs(0.25 - mod(b_cd - f_cd,1.0)) + abs(0.25 - mod(f_cd - a_cd, 1.0))
    #ef_coords
    loss += (0.5 - mod(a_ef-b_ef, 1.0))^2 + (0.5 - mod(c_ef-d_ef,1.0))^2
    #loss += abs(0.25 - mod(a_ef - c_ef, 1.0)) + abs(0.25 - mod(c_ef - b_ef, 1.0))  + abs(0.25 - mod(b_ef - d_ef,1.0)) + abs(0.25 - mod(d_ef - a_ef, 1.0)) 

    return loss
end

loss_1 (generic function with 1 method)

In [51]:
# Loss function 0.5 instead of pi

function loss_2(points, coord_ab, coord_cd, coord_ef)
    a_cd = mod(coord_cd[points[1]],1.0)
    b_cd = mod(coord_cd[points[2]],1.0)

    c_ab = mod(coord_ab[points[3]],1.0)
    d_ab = mod(coord_ab[points[4]],1.0)

    e_ab = mod(coord_ab[points[5]],1.0)
    f_ab = mod(coord_ab[points[6]],1.0)

    e_cd = mod(coord_cd[points[5]],1.0)
    f_cd = mod(coord_cd[points[6]],1.0)

    a_ef = mod(coord_ef[points[1]],1.0)
    b_ef = mod(coord_ef[points[2]],1.0)
    c_ef = mod(coord_ef[points[3]],1.0)
    d_ef = mod(coord_ef[points[4]],1.0)

    # ab_coords
    #loss = abs(0.5 - mod(c_ab-d_ab, 1.0)) + abs(0.5 - mod(e_ab-f_ab,1.0))
    loss = (0.25 - mod(c_ab - e_ab, 1.0))^2 + (0.25 - mod(e_ab - d_ab, 1.0))^2 + (0.25 - mod(d_ab - f_ab,1.0))^2 + + (0.25 - mod(f_ab - c_ab, 1.0))^2
    #cd_coords
    #loss += abs(0.5 - mod(a_cd-b_cd, 1.0)) + abs(0.5 - mod(e_cd-f_cd,1.0))
    loss += (0.25 - mod(a_cd - e_cd, 1.0))^2 + (0.25 - mod(e_cd - b_cd, 1.0))^2 + (0.25 - mod(b_cd - f_cd,1.0))^2 + (0.25 - mod(f_cd - a_cd, 1.0))^2
    #ef_coords
    #loss += abs(0.5 - mod(a_ef-b_ef, 1.0)) + abs(0.5 - mod(c_ef-d_ef,1.0))
    loss += (0.25 - mod(a_ef - c_ef, 1.0))^2 + (0.25 - mod(c_ef - b_ef, 1.0))^2  + (0.25 - mod(b_ef - d_ef,1.0))^2 + (0.25 - mod(d_ef - a_ef, 1.0))^2 

    return loss
end

loss_2 (generic function with 1 method)

In [52]:
# Load Data
matrix = readdlm(input_file, ',', Float64)
data = []
for row in 1:length(matrix[:,1])
    arr = [matrix[row,i] for i in 1:length(matrix[1,:])]
    push!(data, arr)
end

# Do zeroth iteration of algerithm with random points

# Random distinct start points,
# Could be issues with distinct points yielding same piercing hole, and therefore cant do MV
a_0,b_0,c_0,d_0,e_0,f_0 = rand(1:15), rand(15:30), rand(30:45), rand(45:60), rand(60:75), rand(75:100)


# Store to see progress 
"""
push!(a_, a_0)
push!(b_, b_0)
push!(c_, c_0)
push!(d_, d_0)
push!(e_, e_0)
push!(f_, f_0)
"""

data_matrix = zeros(Float64, (3, length(data)))
    
for col in 1:length(data)
    data_matrix[:,col] = [data[col][1],data[col][2],data[col][3]]
end

kdtree = KDTree(data_matrix)





KDTree{StaticArraysCore.SVector{3, Float64}, Euclidean, Float64}
  Number of points: 200
  Dimensions: 3
  Metric: Euclidean(0.0)
  Reordered: true

In [53]:
"""
FIND BEST POINTS....
"""
vec_0 = Array([1,0,0])
vec_1 = Array([0,1,0])
vec_2 = Array([0,0,1])

a_0_set, dists = knn(kdtree, vec_0,K, true)
c_0_set, dists = knn(kdtree, vec_1,K, true)
e_0_set, dists = knn(kdtree, vec_2,K, true)

vec_0 = Array([-1,0,0])
vec_1 = Array([0,-1,0])
vec_2 = Array([0,0,-1])

b_0_set, dists = knn(kdtree, vec_0,K, true)
d_0_set, dists = knn(kdtree, vec_1,K, true)
f_0_set, dists = knn(kdtree, vec_2,K, true)


push!(a_, a_0_set[1])
push!(b_, b_0_set[1])
push!(c_, c_0_set[1])
push!(d_, d_0_set[1])
push!(e_, e_0_set[1])
push!(f_, f_0_set[1])


1-element Vector{Any}:
 40

In [54]:
sisi =  [a_0_set[1]-1, b_0_set[1]-1, c_0_set[1]-1, d_0_set[1]-1, e_0_set[1]-1, f_0_set[1]-1]

6-element Vector{Int64}:
  44
  70
 108
 132
 145
  39

In [55]:
#min_loss_2  = 100   
for k in 1:ITER
    NN = length(a_)
    #points = [a_[NN], b_[NN], c_[NN], d_[NN], e_[NN], f_[NN]]
    points = [a_0_set[1], b_0_set[1], c_0_set[1], d_0_set[1], e_0_set[1], f_0_set[1]]

    mv(points = points, start_points = true, input_file = input_file, output_file = output_file, double_penetration = true, tripple = true)
    # indexing from 2 because c
    matrix = readdlm(output_file * ".csv", ',')
    coord_ab = matrix[2:end,4]

    matrix = readdlm(output_file * "double" * ".csv", ',')
    coord_cd = matrix[2:end,4]

    matrix = readdlm(output_file * "tripple" * ".csv", ',')
    coord_ef = matrix[2:end,4]



    
    a_0 = points[1]
    b_0 = points[2]
    c_0 = points[3]
    d_0 = points[4]
    e_0 = points[5]
    f_0 = points[6]
    #println("Points ", points)

    l = length(a_)
    println("points")
    println("[" * string(a_[l]-1) * "," * string(b_[l]-1) * "," * string(c_[l]-1) * "," 
    * string(d_[l]-1) * "," * string(e_[l]-1) *  "," * string(f_[l]-1) * "]")
    println("-------")
    if k == 1
        min_loss = loss_1([a_0,b_0,c_0,d_0, e_0, f_0], coord_ab, coord_cd, coord_ef)
        min_loss_2 = loss_2([a_0,b_0,c_0,d_0, e_0, f_0], coord_ab, coord_cd, coord_ef) 
        
        # Init Loss
        println("Init Loss: ", min_loss)
        println("Init Loss2: ", min_loss_2)
        push!(loss_, min_loss)
        push!(loss_2, min_loss)
    else
        println("Loss: ", min_loss, " ---- Loss2: ", min_loss_2)
        push!(loss_, min_loss)
        push!(loss_2, min_loss)
    end
    

    ####
    #We move one both points in each pair
    ####

    # See if stationary
    old_b = b_0
    old_d = d_0
    old_f = f_0
    old_a = a_0
    old_c = c_0
    old_e = e_0



    bol1 = true
    bol2 = true
    bol3 = true


    vec_0 = Array([data[b_0][1],data[b_0][2],data[b_0][3]])
    vec_1 = Array([data[d_0][1],data[d_0][2],data[d_0][3]])
    vec_2 = Array([data[f_0][1],data[f_0][2],data[f_0][3]])
    
    b_0_set, dists = knn(kdtree, vec_0,K, true)
    d_0_set, dists = knn(kdtree, vec_1,K, true)
    f_0_set, dists = knn(kdtree, vec_2,K, true)


    vec_0 = Array([data[a_0][1],data[a_0][2],data[a_0][3]])
    vec_1 = Array([data[c_0][1],data[c_0][2],data[c_0][3]])
    vec_2 = Array([data[e_0][1],data[e_0][2],data[e_0][3]])

    a_0_set, dists = knn(kdtree, vec_0,K, true)
    c_0_set, dists = knn(kdtree, vec_1,K, true)
    e_0_set, dists = knn(kdtree, vec_2,K, true)

    # find b_0^i and d_0^1 that minimizes loss



    a_0_i = a_0
    c_0_i = c_0
    e_0_i = e_0

    b_0_i = b_0
    d_0_i = d_0
    f_0_i = f_0
     
    if mod(k, 2) == 0
        if bol1
            for i in 1:length(b_0_set)
                b_0_i = b_0_set[i]
                l = loss_1([a_0,b_0_i,c_0,d_0, e_0, f_0], coord_ab, coord_cd, coord_ef)
                if  l < min_loss
                    min_loss = l
                    b_0 = b_0_i
                    bol1 = false
                end
            end
        end
        if bol2
            for i in 1:length(c_0_set)
                c_0_i  = c_0_set[i]
                l = loss_1([a_0,b_0,c_0_i,d_0, e_0, f_0], coord_ab, coord_cd, coord_ef)
                if  l < min_loss
                    min_loss = l
                    c_0 = c_0_i
                    bol2 = false
                end
            end
        end
    
        if bol2
            for i in 1:length(d_0_set)
                d_0_i  = d_0_set[i]
                l = loss_1([a_0,b_0,c_0,d_0_i, e_0, f_0], coord_ab, coord_cd, coord_ef)
                if  l < min_loss
                    min_loss = l
                    d_0 = d_0_i
                    #bol1 = false
                end
            end
        end
        if bol3
            for i in 1:length(e_0_set)
                e_0_i  = e_0_set[i]
                l = loss_1([a_0,b_0,c_0,d_0, e_0_i, f_0], coord_ab, coord_cd, coord_ef)
                if  l < min_loss
                    min_loss = l
                    e_0 = e_0_i
                    bol3 = false
                end
            end
        end
        if bol3
            for i in 1:length(f_0_set)
                f_0_i  = f_0_set[i]
                l = loss_1([a_0,b_0,c_0,d_0, e_0, f_0_i], coord_ab, coord_cd, coord_ef)
                if  l < min_loss
                    min_loss = l
                    f_0 = f_0_i
                end
            end
        end

    else
        println(" DOing the other loss function")
        if bol1
            for i in 1:length(b_0_set)
                b_0_i = b_0_set[i]
                l = loss_2([a_0,b_0_i,c_0,d_0, e_0, f_0], coord_ab, coord_cd, coord_ef)
                if  l < min_loss_2
                    min_loss_2 = l
                    b_0 = b_0_i
                    bol1 = false
                end
            end
        end
        if bol2
            for i in 1:length(c_0_set)
                c_0_i  = c_0_set[i]
                l = loss_2([a_0,b_0,c_0_i,d_0, e_0, f_0], coord_ab, coord_cd, coord_ef)
                if  l < min_loss_2
                    min_loss_2 = l
                    c_0 = c_0_i
                    bol2 = false
                end
            end
        end
    
        if bol2
            for i in 1:length(d_0_set)
                d_0_i  = d_0_set[i]
                l = loss_2([a_0,b_0,c_0,d_0_i, e_0, f_0], coord_ab, coord_cd, coord_ef)
                if  l < min_loss_2
                    min_loss_2 = l
                    d_0 = d_0_i
                    #bol1 = false
                end
            end
        end
        if bol3
            for i in 1:length(e_0_set)
                e_0_i  = e_0_set[i]
                l = loss_2([a_0,b_0,c_0,d_0, e_0_i, f_0], coord_ab, coord_cd, coord_ef)
                if  l < min_loss_2
                    min_loss_2 = l
                    e_0 = e_0_i
                    bol3 = false
                end
            end
        end
        if bol3
            for i in 1:length(f_0_set)
                f_0_i  = f_0_set[i]
                l = loss_2([a_0,b_0,c_0,d_0, e_0, f_0_i], coord_ab, coord_cd, coord_ef)
                if  l < min_loss_2
                    min_loss_2 = l
                    f_0 = f_0_i
                end
            end
        end


    end
    #println("LOSS 2 ", min_loss_2)
 

    if old_b == b_0 && old_d == d_0 && old_f == f_0 && old_a == a_0 && old_c == c_0 && old_e == e_0
        println("FIXX POINTT")
        break_count -=1
        if break_count == 0
            break
        end
        #break
        #K += 10
        #println("K = ", K)
    else
        break_count = KKK 
    end
    push!(a_, a_0)
    push!(b_, b_0)
    push!(c_, c_0)
    push!(d_, d_0)
    push!(e_, e_0)
    push!(f_, f_0)



    println("Done with: ", k)

end

Number of points: 200 


Careful if this number is too high: 19003
number of 1-simps: 

639
 
number of all simps: 2462
Starting second penetration


number of 1-simps: 

639
 
number of all simps: 2462
Starting third penetration


number of 1-simps: 

639
 
number of all simps: 2462
All penetration done.


points
[44,70,108,132,145,39]
-------
Init Loss: 0.0076322280723013745
Init Loss222: 0.0076322280723013745
 DOing the other loss function
Done with: 1
Number of points: 200 


Careful if this number is too high: 19003
number of 1-simps: 

639
 
number of all simps: 2462
Starting second penetration


number of 1-simps: 

639
 
number of all simps: 2462
Starting third penetration


number of 1-simps: 

639
 
number of all simps: 2462
All penetration done.


points
[44,91,108,132,159,39]
-------
Loss: 0.0076322280723013745 ---- Loss2: 2.007760586561238
Done with: 2
Number of points: 200 
Careful if this number is too high: 

19003


number of 1-simps: 639
 
number of all simps: 2462


Starting second penetration


number of 1-simps: 639
 
number of all simps: 2462


Starting third penetration


number of 1-simps: 639
 
number of all simps: 2462


All penetration done.
points
[44,2,108,132,159,39]
-------
Loss: 0.0020058200466486096 ---- Loss2: 2.007760586561238
 DOing the other loss function
FIXX POINTT
Done with: 3
Number of points: 200 


Careful if this number is too high: 19003
number of 1-simps: 

639
 
number of all simps: 2462
Starting second penetration


number of 1-simps: 

639
 
number of all simps: 2462
Starting third penetration


number of 1-simps: 

639
 
number of all simps: 2462
All penetration done.


points
[44,70,108,132,145,39]
-------
Loss: 0.0020058200466486096 ---- Loss2: 2.007760586561238
FIXX POINTT


In [56]:
loss_

4-element Vector{Any}:
 0.0076322280723013745
 0.0076322280723013745
 0.0020058200466486096
 0.0020058200466486096

In [ ]:
loss_2

In [57]:
println("Input:")
println("[" * string(a_[1]-1) * "," * string(b_[1]-1) * ","
 * string(c_[1]-1) * "," * string(d_[1]-1) *  "," * string(e_[1]-1) *  "," * string(f_[1]-1) * "]")

Input:
[44,70,108,132,145,39]


In [58]:
l = length(a_)
println("Output:")
println("[" * string(a_[l]-1) * "," * string(b_[l]-1) * "," * string(c_[l]-1) * "," 
* string(d_[l]-1) * "," * string(e_[l]-1) *  "," * string(f_[l]-1) * "]")

Output:
[44,70,108,132,145,39]
